### ISSUE TITLE
[META] List of blocking issues for Drupal that we should also look at

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/ckeditor5#36]
I'm making a list of these issues for one of my client projects, so I thought I could document them here also. I believe we already have issues for some of these things, and some of them have already been fixed for Backdrop, so I won't make the individual issues yet, but I'll include the d.o links for reference.

### Prioritized list
- [x] only `src` attribute allowed on links 
- [x] CKE5 removes `width` & `height` attributes on `<img>` | d.o issue https://www.drupal.org/project/drupal/issues/3321296 
- [x] No styles on block-level elements | d.o issue https://www.drupal.org/project/drupal/issues/3326261
- [x] CKE5 removes empty inline elements (icons added with `<i></i>`) | d.o issue https://www.drupal.org/project/drupal/issues/3337298
- [x] CKE5 removes `<a>`s that wrap HTML elements not natively supported by CKEditor 5 | d.o issue https://www.drupal.org/project/drupal/issues/3349893
- [ ] CKE5 does not allow full-screen editing [drupal.org/project/drupal/issues/3331158](https://www.drupal.org/project/drupal/issues/3331158)

### Other things we should look at
* [#3321254: [upstream] Remove Format button does not remove `style` attributes](https://www.drupal.org/project/drupal/issues/3321254)
* [#3333494: [upstream] CKE5 Code Blocks missing type around wrapper](https://www.drupal.org/project/drupal/issues/3333494)
* [#3335991: [upstream] CKEditor 5 does not retain custom HTML tags that are not defined by CKEditor 5 plugins whenever /.*/ is not allowed (e.g. when filter_html is enabled)](https://www.drupal.org/project/drupal/issues/3335991)
* [#3342874: [upstream] Allow inline HTML comments in ckeditor5](https://www.drupal.org/project/drupal/issues/3342874)
*

**Comment by olafgrabienski** [comment]
Not sure if to consider as 'blocking', but at least a regression:

So far, CKEditor 5 doesn't support Full-screen editing. Should this be mentioned in in the list above, or is it worth a separate issue?

More info:

- CKEditor issue: https://github.com/ckeditor/ckeditor5/issues/1235
(voting for the feature at [issuecomment-918162952](https://github.com/ckeditor/ckeditor5/issues/1235#issuecomment-918162952))
- Drupal issue: https://www.drupal.org/project/drupal/issues/3331158
- Drupal plugin: https://www.drupal.org/project/ckeditor5_fullscreen

**Comment by olafgrabienski** [comment]
An update re [CKE5 removes empty inline elements (icons added with `<i></i>`](https://www.drupal.org/project/drupal/issues/3337298):
This issue is fixed in Drupal by upgrading CKEditor 5 to version 39, see https://www.drupal.org/node/3379650.

**Comment by quicksketch** [comment]
> CKE5 removes width & height attributes on `<img>`

This seems to have been fixed in v.40.0.0

> No styles on block-level elements

This was fixed in https://github.com/ckeditor/ckeditor5/issues/13341, CKEditor v38.0.0

> CKE5 removes `<a>`s that wrap HTML elements not natively supported by CKEditor 5

This was fixed in 38.x.x (not sure which version but upgrading to 40+ should do the trick)

---

So after updating CKEditor to v40+, all our blocking issues should be resolved, other than full-screen editing, which does not yet exist upstream.

**Comment by quicksketch** [comment]
Since all other issues have been addressed, let's split out full screen support into its own issue: https://github.com/backdrop-contrib/ckeditor5/issues/76
